site_name: Spreadsheet Importer
site_description: Importador serverless (XLSX/CSV) com integração Flowch
site_url: https://BrunoSola.github.io/Spreadsheet-Importer
repo_url: https://github.com/BrunoSola/Spreadsheet-Importer
edit_uri: ""

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo claro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Uso: uso.md
  - CSV & XLSX: csv-xlsx.md
  - API/Headers: api.md
  - Troubleshooting: troubleshooting.md
