openapi: 3.0.3
info:
  title: Spreadsheet Importer (XLSX/CSV)
  description: |
    Lambda para importar planilhas **XLSX/CSV**, transformar linhas em registros e enviar para o Flowch.

    **Modos de envio**  
    - **Integração (via endpoint):** encaminha cada registro para sua Lambda de integração (`INTEGRATION_URL`), que então chama o Flowch.  
    - **Direto ao Flowch (via x-endpoint-url):** envia **em lotes** diretamente para um endpoint completo do Flowch.

    **Headers principais**
    - `Authorization` — token **cru** do Flowch (sem `integration `).
    - `endpoint` — **obrigatório no modo Integração** (ignorado se `x-endpoint-url` for enviado).
    - `x-endpoint-url` — **ativa modo Direto** (URL completa do Flowch).
    - `x-batch-size` — tamanho dos lotes no modo Direto (default 20).
    - `x-dry-run` — `"true"` simula (não envia).
    - `x-preview` — `"true"` retorna amostra (até 5 linhas).
    - `x-limit` — processa apenas N linhas do arquivo.

    **Entrada do arquivo**  
    - `multipart/form-data` com a parte `file`  
    **ou**  
    - `application/json` com `{ base64, filename?, contentType? }`.

    **Regras de parsing**
    - 1ª linha é o **cabeçalho** (obrigatório; sem duplicadas; sem nomes vazios).
    - CSV: detecta delimitador automaticamente (`; , \t |`) e trata BOM/latin1 quando necessário.
    - XLSX: lido com ExcelJS, preserva boolean/number e converte Date → ISO quando aplicável.
    - `true/false` → boolean (não string).
    - Datas reconhecidas em strings são normalizadas p/ `"yyyy-MM-dd HH:mm:ss"`.
    - Números com vírgula decimal **são mantidos como string** (ex.: `"10,2"`).

  version: "1.0.0"

servers:
  - url: https://{api_id}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      api_id: { default: your-api-id }
      region: { default: sa-east-1 }
      stage:  { default: prod }

tags:
  - name: Importação
    description: Importa arquivo (XLSX/CSV), transforma e envia conforme o modo escolhido.

paths:
  /import:
    post:
      tags: [Importação]
      summary: Importar planilha e despachar registros (Integração ou Direto)
      description: |
        Envie um **XLSX/CSV** via `multipart/form-data` (campo `file`) **ou** um JSON com `{ base64, filename?, contentType? }`.

        - **Modo Integração:** envie o header `endpoint` (ex.: `"avaliacaoDesempenho"`).  
          A Lambda de integração é lida da variável de ambiente `INTEGRATION_URL`.

        - **Modo Direto:** envie `x-endpoint-url` com a **URL completa do Flowch**.  
          O envio será feito **em lotes** (`x-batch-size`, default 20).

      parameters:
        - in: header
          name: Authorization
          description: Token cru do Flowch (sem prefixo).
          required: true
          schema: { type: string }
          example: aed28a073116dadaf017563f50804cfc

        - in: header
          name: endpoint
          description: Obrigatório no **modo Integração**. Ignorado se `x-endpoint-url` for usado.
          required: false
          schema: { type: string }
          examples:
            avaliacaoDesempenho:
              summary: Exemplo (Integração)
              value: avaliacaoDesempenho

        - in: header
          name: x-endpoint-url
          description: URL **completa** do Flowch (ativa o **modo Direto**).
          required: false
          schema:
            type: string
            format: uri
          examples:
            direto:
              summary: Exemplo (Direto)
              value: https://int01.flowch.com/integrator/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/avaliacaoDesempenho

        - in: header
          name: x-batch-size
          description: Tamanho dos lotes no modo Direto.
          required: false
          schema: { type: integer, default: 20 }
          example: 50

        - in: header
          name: x-dry-run
          description: Se `"true"`, **simula** (não envia).
          required: false
          schema:
            type: string
            enum: ["true", "false"]
          example: "true"

        - in: header
          name: x-preview
          description: Se `"true"`, retorna amostra (até 5 linhas).
          required: false
          schema:
            type: string
            enum: ["true", "false"]
          example: "false"

        - in: header
          name: x-limit
          description: Processa no máximo **N** linhas.
          required: false
          schema: { type: integer, minimum: 1 }
          example: 100

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: Arquivo XLSX/CSV
                  type: string
                  format: binary
            examples:
              xlsx_integra:
                summary: XLSX (modo Integração)
                description: Envio de XLSX com header `endpoint`.
                value: {}
              csv_direto:
                summary: CSV (modo Direto)
                description: Envio de CSV com `x-endpoint-url` para lotes.
                value: {}

          application/json:
            schema:
              type: object
              properties:
                base64:
                  type: string
                  description: Arquivo inteiro em base64 (pode ter dataURL; será removido).
                filename:
                  type: string
                  description: Nome do arquivo (opcional).
                contentType:
                  type: string
                  description: Content-Type do arquivo (opcional).
              required: [base64]
            examples:
              json_integra:
                summary: JSON base64 (Integração)
                value:
                  base64: "UEsDBBQACAAI... (base64 XLSX ou CSV) ..."
                  filename: "dados.xlsx"
                  contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
              json_direto:
                summary: JSON base64 (Direto)
                value:
                  base64: "ZWNvLWRlLWNzdi1lbSB1dGY4IG91IGxhdGluMQo=..."
                  filename: "dados.csv"
                  contentType: "text/csv"

      responses:
        "200":
          description: Sucesso (resumo + detalhes)
          content:
            application/json:
              examples:
                sucesso_integracao:
                  summary: Sucesso – **Modo Integração**
                  value:
                    summary:
                      arquivo: "dados.xlsx"
                      contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                      linhasLidas: 128
                      enviadas: 125
                      jaExistiam: 2
                      erros: 1
                      duracaoMs: 3456
                      dryRun: false
                      preview: false
                      paralelismo: 5
                      batchSize: 5
                    preview: null
                    errosAmostra:
                      - linha: 27
                        endpoint: "avaliacaoDesempenho"
                        status: "ERRO"
                        mensagem: "Campo obrigatório ausente: recibo_cod"
                        upstreamStatus: 400
                        perfMs: 120
                    results:
                      - linha: 2
                        endpoint: "avaliacaoDesempenho"
                        status: "ENVIADO"
                        mensagem: "OK"
                        upstreamStatus: 200
                        perfMs: 98

                sucesso_direto:
                  summary: Sucesso – **Modo Direto (lotes)**
                  value:
                    summary:
                      modo: "direto-flowch"
                      endpointUrl: "https://int01.flowch.com/integrator/uuid/avaliacaoDesempenho"
                      linhasLidas: 1200
                      enviadasAprox: 1180
                      errosBatches: 1
                      duracaoMs: 12987
                      dryRun: false
                      preview: false
                      batchSize: 50
                      totalBatches: 24
                    preview: null
                    batches:
                      - batchIndex: 1
                        size: 50
                        statusCode: 200
                        durationMs: 220
                        body: { accepted: 50 }
                      - batchIndex: 2
                        size: 50
                        statusCode: 500
                        durationMs: 210
                        body: { error: "UPSTREAM_5XX" }

                preview_example:
                  summary: **Pré-visualização** (x-preview:true)
                  value:
                    summary:
                      arquivo: "dados.csv"
                      contentType: "text/csv"
                      linhasLidas: 10
                      enviadas: 0
                      jaExistiam: 0
                      erros: 0
                      duracaoMs: 150
                      dryRun: false
                      preview: true
                      paralelismo: 5
                      batchSize: 5
                    preview:
                      - { nome: "Ana", email: "ana@acme.com", ativo: true,  nota: "10,2", data: "2025-01-31 00:00:00" }
                      - { nome: "Bob", email: "bob@acme.com", ativo: false, nota: "8,7",  data: "2025-02-01 00:00:00" }
                    results: []

                dry_run_example:
                  summary: **Dry-run** (x-dry-run:true)
                  value:
                    summary:
                      modo: "direto-flowch"
                      endpointUrl: "https://int01.flowch.com/integrator/uuid/avaliacaoDesempenho"
                      linhasLidas: 200
                      enviadas: 0
                      jaExistiam: 0
                      erros: 0
                      duracaoMs: 320
                      dryRun: true
                      preview: false
                      batchSize: 20
                    results: []

        "400":
          description: Requisição inválida (headers/arquivo)
          content:
            application/json:
              examples:
                sem_auth:
                  summary: Falta Authorization
                  value: { error: 'Header "Authorization" é obrigatório.' }
                sem_endpoint_e_sem_url:
                  summary: Nem endpoint (integração) nem x-endpoint-url (direto) foram enviados
                  value: { error: 'Header "endpoint" é obrigatório (ou use x-endpoint-url).' }
                arquivo_vazio:
                  summary: Arquivo ausente
                  value: { error: 'Arquivo ausente no body (base64/multipart) ou vazio.' }
                csv_ruim:
                  summary: CSV com cabeçalho inválido
                  value: { error: 'Cabeçalho CSV inválido: colunas duplicadas.' }

        "413":
          description: Arquivo muito grande
          content:
            application/json:
              example: { error: 'Arquivo maior que o permitido (6000000 bytes > 5242880).' }

        "500":
          description: Erro inesperado
          content:
            application/json:
              example: { error: 'Erro inesperado' }
